-- MySQL Script generated by MySQL Workbench
-- 04/21/16 11:32:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`company_field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company_field` (
  `field_id` INT NOT NULL,
  `field_type` VARCHAR(4) NULL,
  `field_name` VARCHAR(45) NULL,
  PRIMARY KEY (`field_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agent` (
  `agent_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `agent_email` VARCHAR(45) NULL,
  `agent_phone` VARCHAR(45) NULL,
  `agent_address` VARCHAR(45) NULL,
  `agent_first_name` VARCHAR(15) NULL,
  `agent_last_name` VARCHAR(15) NULL,
  PRIMARY KEY (`agent_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`headquarter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`headquarter` (
  `headquarter_id` INT NOT NULL AUTO_INCREMENT,
  `headquarter_city` VARCHAR(30) NULL,
  PRIMARY KEY (`headquarter_id`),
  UNIQUE INDEX `headquarter_id_UNIQUE` (`headquarter_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_field_id` INT NOT NULL,
  `agent_id` INT UNSIGNED NOT NULL,
  `headquarter_id` INT NOT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`company_id`),
  UNIQUE INDEX `company_id_UNIQUE` (`company_id` ASC),
  INDEX `fk_company_company_field_idx` (`company_field_id` ASC),
  INDEX `fk_company_agent1_idx` (`agent_id` ASC),
  INDEX `fk_company_headquarter1_idx` (`headquarter_id` ASC),
  CONSTRAINT `fk_company_company_field`
    FOREIGN KEY (`company_field_id`)
    REFERENCES `mydb`.`company_field` (`field_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_agent1`
    FOREIGN KEY (`agent_id`)
    REFERENCES `mydb`.`agent` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_headquarter1`
    FOREIGN KEY (`headquarter_id`)
    REFERENCES `mydb`.`headquarter` (`headquarter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_report` (
  `date` DATE NOT NULL,
  `open` DOUBLE NOT NULL,
  `high` DOUBLE NOT NULL,
  `low` DOUBLE NOT NULL,
  `close` DOUBLE NOT NULL,
  `volume` INT NOT NULL,
  `adj_close` DOUBLE NOT NULL,
  `company_id` INT NOT NULL,
  `stock_id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_stock_report_company1_idx` (`company_id` ASC),
  PRIMARY KEY (`stock_id`),
  CONSTRAINT `fk_stock_report_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock_holder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_holder` (
  `stock_holder_id` INT NOT NULL AUTO_INCREMENT,
  `stock_holder_first_name` VARCHAR(30) NULL,
  `stock_holder_last_name` VARCHAR(30) NULL,
  `company_id` INT NOT NULL,
  `stock_holder_address` VARCHAR(45) NULL,
  `stock_holder_email` VARCHAR(45) NULL,
  PRIMARY KEY (`stock_holder_id`),
  UNIQUE INDEX `sh_id_UNIQUE` (`stock_holder_id` ASC),
  INDEX `fk_stock_holders_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_stock_holders_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

source agent.sql

source QuickSetup.sql

source stockholder.sql

source microsoft_2016-04-14.sql

source intel_2016-04-19.sql

source nvidia_2016-04-21.sql

source amd_2016-04-21.sql

source broadcom_2016-04-21.sql

delete from stock_report
	where company_id = 1
	and stock_id > 499 +
		(select min(stock_id) as min_stock_id from
			(select stock_id from stock_report as x
			where company_id = 1) as y);
			
delete from stock_report
	where company_id = 2
	and stock_id > 499 +
		(select min(stock_id) as min_stock_id from
			(select stock_id from stock_report as x
			where company_id = 2) as y);

delete from stock_report
	where company_id = 3
	and stock_id > 499 +
		(select min(stock_id) as min_stock_id from
			(select stock_id from stock_report as x
			where company_id = 3) as y);

delete from stock_report
	where company_id = 4
	and stock_id > 499 +
		(select min(stock_id) as min_stock_id from
			(select stock_id from stock_report as x
			where company_id = 4) as y);
		
delete from stock_report
	where company_id = 5
	and stock_id > 499 +
		(select min(stock_id) as min_stock_id from
			(select stock_id from stock_report as x
			where company_id = 5) as y);
